### PR TITLE
Make making new users consistent

### PR DESCRIPTION
**Pull request by CosSinII**
Previously how names were formatted depended on if they were introduced to the system by being nominated or logging in. Now both take the display name from Hoodis. PersonContoller also adds people a different way but I don't understand it enough to touch it.

### CODE REVIEW

**Review by mathiasmagnusson — CHANGES_REQUESTED** [review]
In the `AuthController`, we're requesting data from login, which does not provide a `displayName` (which hodis does, so the `NominationController` does get it).

Login currently returns the following fields:

https://github.com/datasektionen/login/blob/2139590be3e5e996d56a9231d89562f3d1071d3b/kth_ldap.py#L26-L30

So either we should keep it as `$body->first_name . " " . $body->last_name;` or make login also return a display name.

**Comment by Herkarl** [comment]
Cool! I've been wondering what caused this behaviour for quite a few years now. Nice find.

I would argue for the the first of the options Mathias mentioned, partly because it seems like an easier fix that doesn't change API bahaviour. But mostly because the `displayName` contains the KTH-id of the user (`Herman Karlsson (hermanka)`), which I think looks worse.

**Comment by mathiasmagnusson** [comment]
The changes have already been applied retroactively in the database and the way names are displayed has changed, so it's just how we create new users that has to change.

The `displayName` from hodis actually does not include the kth-id, but hodis also returns a `cn` which does.

**Comment by Herkarl** [comment]
Ah ok, nice 👍 makes sense

**Comment by mathiasmagnusson** [comment]
I can't remember closing this or it being solved. Did I missclick or have i forgotten?

**Comment by mathiasmagnusson** [comment]
Whaaat

**Comment by Herkarl** [comment]
????

**Comment by mathiasmagnusson** [comment]
:magic_wand:

**Pull request closed without merging**
