### PR TITLE
Make only one set of filtering options for all elections (which is already how they behave)

### LINKED ISSUE #37: Filtreringsalternativen uppdateras ej på alla ställen
Det att välja filtreringsalternativ på fler än ett ställe när det är både val och fyllnadsval.
De verkar vara kopplade till samma variabler i båda ställen. Däremot förändras inte de korresponderande checkboxarna på det andra stället.

Förslag är att bara ha checkboxes på ett ställe, känns märkligt att vilja filtrera olika för de två sektionerna.

image

### PR DESCRIPTION
**Pull request by mathiasmagnusson**
Fixes #37

### CODE REVIEW

**Review by Herkarl — APPROVED** [review]
will look like this

Thought it would lok worse, but I think it's fine.

**Comment by Herkarl** [comment]
I think it would be fairly easy to make it work separately for each election, you just have to make sure things have the right keys, but I also think that you most often would want the same setting for all elections.

Worth noting is that this will result in the checkboxes being visible when no election is open. But I think I think that is fine

**Comment by mathiasmagnusson** [comment]
Unless i made a bug, the checkboxes will only be shown when there is at least one election visible.

And I agree that it looks a little weird. Perhaps putting them on the side would be better?

**Comment by Herkarl** [comment]
Right, I forgot the `@if` you added :stuck_out_tongue:, nvm then.

I'm a bit unsure if having it on the side is better, I think the horizontal space is better used to display more elections. But it is true that there is some leftover space on the sides that could be used, so if it is possible to format the text in a nice way in that space it would probably be nice. It could also have the advantage of having the checkboxes follow when scrolling, which I think would be nice. On mobile the checkboxes would probably have to be at the top though, to little space for anything else, I think.

**Comment by Herkarl** [comment]
Sounds good :+1:

**Pull request merged**
